trigger:
- master

strategy:
  matrix:
    linux:
      operatingSystem: 'ubuntu-latest'
    mac:
      operatingSystem: 'macos-latest'

pool:
  vmImage: $(operatingSystem)

stages:
- stage: build
  jobs:
  - job: run_build
    pool:
      vmImage: $(operatingSystem)
    steps:
    - script: echo Build
    
- stage: staging
  dependsOn: build
  jobs:
  - job: deploy_staging
    pool:
      vmImage: $(operatingSystem)
    steps:
    - script: echo Staging

- stage: prod
  dependsOn: staging
  jobs:
  - job: deploy_prod
    pool:
      vmImage: $(operatingSystem)
    steps:
    - script: echo Prod